-- cave.lua
-- Neovim colorscheme inspired by Noita and Catppuccin.

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
	vim.cmd("syntax reset")
end

vim.g.colors_name = "cave"
vim.o.background = "dark"
vim.o.termguicolors = true

local p = {
	air              = "#f4f0e8",
	bone             = "#d4c8a8",
	gold             = "#e8d030",
	spark            = "#20d8f0",
	fungus           = "#c85ca8",
	lake             = "#4e8fd4",
	fog              = "#8868c0",
	amber            = "#c89030",
	acid             = "#9cc028",
	sea              = "#20b8a0",
	lava             = "#d46818",
	danger           = "#e03030",
	cloak            = "#6a3a9a",
	blood            = "#c03838",
	ash              = "#6e6458",
	emerald          = "#3d8c5a",
	wall             = "#3a3040",
	deep             = "#1e1a28",
	soil             = "#331215",
	grass            = "#172a18",
	oil              = "#1b1512",
	shadow           = "#130f16",
	void             = "#060408",
}

-- ── Highlight table ──────────────────────────────────────────────────────────
-- String values are treated as links in the apply loop below.
local hl = {

	-- ── Base Vim ──────────────────────────────────────────────────────────────
	Normal = { fg = p.bone, bg = p.shadow },
	NormalNC = "Normal",
	NormalFloat = { fg = p.bone, bg = p.void },
	FloatBorder = { fg = p.cloak, bg = p.void },
	FloatTitle = { fg = p.lake, bg = p.void, bold = true },
	ColorColumn = { bg = p.shadow },
	Conceal = { fg = p.ash },
	Cursor = { fg = p.void, bg = p.air },
	lCursor = "Cursor",
	CursorIM = "Cursor",
	CursorLine = { bg = p.deep },
	CursorColumn = { bg = p.deep },
	CursorLineNr = { fg = p.lake, bold = true },
	Directory = { fg = p.lake },
	DiffAdd = { bg = p.grass, fg = p.air },
	DiffChange = { bg = p.oil, fg = p.lava },
	DiffDelete = { bg = p.soil, fg = p.air },
	DiffText = { bg = p.lava, fg = p.air },
	EndOfBuffer = { fg = p.void },
	ErrorMsg = { fg = p.danger, bold = true },
	VertSplit = { fg = p.cloak, bg = p.void },
	WinSeparator = { fg = p.cloak, bg = p.void },
	Folded = { fg = p.ash, bg = p.shadow },
	FoldColumn = { fg = p.wall, bg = p.void },
	SignColumn = { fg = p.bone, bg = p.void },
	IncSearch = { fg = p.void, bg = p.lava, bold = true },
	YankFlash = { bg = p.spark, fg = p.void },
	Substitute = { fg = p.void, bg = p.blood, bold = true },
	LineNr = { fg = p.wall },
	LineNrAbove = { fg = p.wall },
	LineNrBelow = { fg = p.wall },
	MatchParen = { fg = p.gold, bold = true, underline = true },
	ModeMsg = { fg = p.lake, bold = true },
	MsgArea = { fg = p.bone },
	MsgSeparator = { fg = p.cloak },
	MoreMsg = { fg = p.emerald },
	NonText = { fg = p.fog },
	Pmenu = { fg = p.fog, bg = p.void },
	PmenuSel = { fg = p.bone, bg = p.lake },
	PmenuSbar = { bg = p.shadow },
	PmenuThumb = { bg = p.cloak },
	PmenuKind = { fg = p.blood, bg = p.void },
	PmenuKindSel = { fg = p.blood, bg = p.lake },
	PmenuExtra = { fg = p.ash, bg = p.void },
	PmenuExtraSel = { fg = p.ash, bg = p.lake },
	Question = { fg = p.lake },
	QuickFixLine = { bg = p.deep },
	Search = { fg = p.void, bg = p.gold, bold = true },
	SpecialKey = { fg = p.ash },
	SpellBad = { undercurl = true, sp = p.danger },
	SpellCap = { undercurl = true, sp = p.lava },
	SpellLocal = { undercurl = true, sp = p.emerald },
	SpellRare = { undercurl = true, sp = p.amber },
	StatusLine = { fg = p.bone, bg = p.shadow },
	StatusLineNC = { fg = p.ash, bg = p.shadow },
	TabLine = { fg = p.ash, bg = p.shadow },
	TabLineFill = { bg = p.shadow },
	TabLineSel = { fg = p.bone, bg = p.cloak },
	Title = { fg = p.lake, bold = true },
	Visual = { bg = p.fog, fg = p.bone },
	VisualNOS = { bg = p.fog, fg = p.bone },
	WarningMsg = { fg = p.lava, bold = true },
	Whitespace = { fg = p.wall },
	WildMenu = { fg = p.bone, bg = p.cloak },
	WinBar = { fg = p.bone, bg = p.shadow },
	WinBarNC = { fg = p.ash, bg = p.shadow },

	-- ── Syntax ────────────────────────────────────────────────────────────────
	Comment = { fg = p.emerald, italic = true },
	Constant = { fg = p.amber },
	String = { fg = p.acid },
	Character = { fg = p.acid },
	Number = { fg = p.amber },
	Boolean = { fg = p.amber },
	Float = { fg = p.amber },
	Identifier = { fg = p.fog },
	Function = { fg = p.fungus },
	Statement = { fg = p.lake },
	Conditional = { fg = p.lake },
	Repeat = { fg = p.lake },
	Label = { fg = p.lake },
	Operator = { fg = p.bone },
	Keyword = { fg = p.lake },
	Exception = { fg = p.blood },
	PreProc = { fg = p.lake },
	Include = { fg = p.lake },
	Define = { fg = p.lake },
	Macro = { fg = p.lake },
	PreCondit = { fg = p.lake },
	Type = { fg = p.blood },
	StorageClass = { fg = p.blood },
	Structure = { fg = p.blood },
	Typedef = { fg = p.blood },
	Special = { fg = p.amber },
	SpecialChar = { fg = p.acid },
	Tag = { fg = p.lake },
	Delimiter = { fg = p.bone },
	SpecialComment = { fg = p.emerald, italic = true },
	Debug = { fg = p.lava },
	Underlined = { underline = true },
	Ignore = { fg = p.ash },
	Error = { fg = p.danger, bold = true },
	Todo = { fg = p.void, bg = p.lake, bold = true },

	-- ── Treesitter ────────────────────────────────────────────────────────────
	["@variable"] = { fg = p.fog },
	["@variable.builtin"] = { fg = p.lake },
	["@variable.parameter"] = { fg = p.fog },
	["@variable.member"] = { fg = p.fog },
	["@constant"] = { fg = p.amber },
	["@constant.builtin"] = { fg = p.amber, bold = true },
	["@constant.macro"] = { fg = p.amber },
	["@module"] = { fg = p.bone },
	["@module.builtin"] = { fg = p.lake },
	["@label"] = { fg = p.lake },
	["@string"] = { fg = p.acid },
	["@string.documentation"] = { fg = p.acid, italic = true },
	["@string.regexp"] = { fg = p.lava },
	["@string.escape"] = { fg = p.blood },
	["@string.special"] = { fg = p.amber },
	["@string.special.symbol"] = { fg = p.amber },
	["@string.special.url"] = { fg = p.sea, underline = true },
	["@character"] = { fg = p.acid },
	["@character.special"] = { fg = p.amber },
	["@number"] = { fg = p.amber },
	["@number.float"] = { fg = p.amber },
	["@boolean"] = { fg = p.amber, bold = true },
	["@function"] = { fg = p.fungus },
	["@function.builtin"] = { fg = p.fungus, bold = true },
	["@function.call"] = { fg = p.fungus },
	["@function.macro"] = { fg = p.fungus },
	["@function.method"] = { fg = p.fungus },
	["@function.method.call"] = { fg = p.fungus },
	["@constructor"] = { fg = p.blood },
	["@operator"] = { fg = p.bone },
	["@keyword"] = { fg = p.lake },
	["@keyword.coroutine"] = { fg = p.lake },
	["@keyword.function"] = { fg = p.lake },
	["@keyword.operator"] = { fg = p.lake },
	["@keyword.import"] = { fg = p.lake },
	["@keyword.storage"] = { fg = p.blood },
	["@keyword.repeat"] = { fg = p.lake },
	["@keyword.return"] = { fg = p.lake },
	["@keyword.debug"] = { fg = p.lava },
	["@keyword.exception"] = { fg = p.blood },
	["@keyword.conditional"] = { fg = p.lake },
	["@keyword.conditional.ternary"] = { fg = p.lake },
	["@keyword.directive"] = { fg = p.lake },
	["@keyword.directive.define"] = { fg = p.lake },
	["@punctuation.delimiter"] = { fg = p.ash },
	["@punctuation.bracket"] = { fg = p.bone },
	["@punctuation.special"] = { fg = p.blood },
	["@comment"] = { fg = p.emerald, italic = true },
	["@comment.documentation"] = { fg = p.emerald, italic = true },
	["@comment.error"] = { fg = p.danger, bold = true },
	["@comment.warning"] = { fg = p.lava, bold = true },
	["@comment.todo"] = { fg = p.void, bg = p.lake, bold = true },
	["@comment.note"] = { fg = p.void, bg = p.emerald, bold = true },
	["@type"] = { fg = p.blood },
	["@type.builtin"] = { fg = p.blood, bold = true },
	["@type.definition"] = { fg = p.blood },
	["@attribute"] = { fg = p.ash },
	["@attribute.builtin"] = { fg = p.ash },
	["@property"] = { fg = p.fog },
	["@tag"] = { fg = p.lake },
	["@tag.builtin"] = { fg = p.lake },
	["@tag.attribute"] = { fg = p.fog },
	["@tag.delimiter"] = { fg = p.ash },
	["@diff.plus"] = { bg = p.grass, fg = p.air },
	["@diff.minus"] = { bg = p.soil, fg = p.air },
	["@diff.delta"] = { bg = p.oil, fg = p.lava },
	["@markup.strong"] = { bold = true },
	["@markup.italic"] = { italic = true },
	["@markup.strikethrough"] = { strikethrough = true },
	["@markup.underline"] = { underline = true },
	["@markup.heading"] = { fg = p.lake, bold = true },
	["@markup.heading.1"] = { fg = p.lake, bold = true },
	["@markup.heading.2"] = { fg = p.emerald, bold = true },
	["@markup.heading.3"] = { fg = p.acid, bold = true },
	["@markup.heading.4"] = { fg = p.amber },
	["@markup.heading.5"] = { fg = p.ash },
	["@markup.heading.6"] = { fg = p.ash },
	["@markup.quote"] = { fg = p.emerald, italic = true },
	["@markup.math"] = { fg = p.blood },
	["@markup.link"] = { fg = p.lake, underline = true },
	["@markup.link.label"] = { fg = p.lake },
	["@markup.link.url"] = { fg = p.sea, underline = true },
	["@markup.raw"] = { fg = p.bone, bg = p.shadow },
	["@markup.raw.block"] = { fg = p.bone, bg = p.shadow },
	["@markup.list"] = { fg = p.lake },
	["@markup.list.checked"] = { fg = p.acid },
	["@markup.list.unchecked"] = { fg = p.ash },

	-- ── LSP semantic tokens ───────────────────────────────────────────────────
	["@lsp.type.class"] = "@type",
	["@lsp.type.comment"] = "@comment",
	["@lsp.type.decorator"] = "@attribute",
	["@lsp.type.enum"] = "@type",
	["@lsp.type.enumMember"] = "@constant",
	["@lsp.type.event"] = "@type",
	["@lsp.type.function"] = "@function",
	["@lsp.type.interface"] = "@type",
	["@lsp.type.keyword"] = "@keyword",
	["@lsp.type.macro"] = "@constant.macro",
	["@lsp.type.method"] = "@function.method",
	["@lsp.type.modifier"] = "@keyword",
	["@lsp.type.namespace"] = "@module",
	["@lsp.type.number"] = "@number",
	["@lsp.type.operator"] = "@operator",
	["@lsp.type.parameter"] = "@variable.parameter",
	["@lsp.type.property"] = "@property",
	["@lsp.type.regexp"] = "@string.regexp",
	["@lsp.type.string"] = "@string",
	["@lsp.type.struct"] = "@type",
	["@lsp.type.type"] = "@type",
	["@lsp.type.typeParameter"] = "@type",
	["@lsp.type.variable"] = "@variable",
	["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
	["@lsp.typemod.variable.defaultLibrary"] = "@variable.builtin",
	["@lsp.typemod.type.defaultLibrary"] = "@type.builtin",

	-- ── Diagnostics ───────────────────────────────────────────────────────────
	DiagnosticError = { fg = p.danger },
	DiagnosticWarn = { fg = p.lava },
	DiagnosticInfo = { fg = p.lake },
	DiagnosticHint = { fg = p.emerald },
	DiagnosticOk = { fg = p.emerald },
	DiagnosticVirtualTextError = { fg = p.danger, bg = p.soil, italic = true },
	DiagnosticVirtualTextWarn = { fg = p.lava, bg = p.fungus, italic = true },
	DiagnosticVirtualTextInfo = { fg = p.lake, bg = p.deep, italic = true },
	DiagnosticVirtualTextHint = { fg = p.emerald, bg = p.grass, italic = true },
	DiagnosticVirtualTextOk = { fg = p.emerald, bg = p.grass, italic = true },
	DiagnosticUnderlineError = { undercurl = true, sp = p.danger },
	DiagnosticUnderlineWarn = { undercurl = true, sp = p.lava },
	DiagnosticUnderlineInfo = { undercurl = true, sp = p.lake },
	DiagnosticUnderlineHint = { undercurl = true, sp = p.emerald },
	DiagnosticUnderlineOk = { undercurl = true, sp = p.emerald },
	DiagnosticFloatingError = { fg = p.danger },
	DiagnosticFloatingWarn = { fg = p.lava },
	DiagnosticFloatingInfo = { fg = p.lake },
	DiagnosticFloatingHint = { fg = p.emerald },
	DiagnosticSignError = { fg = p.danger },
	DiagnosticSignWarn = { fg = p.lava },
	DiagnosticSignInfo = { fg = p.lake },
	DiagnosticSignHint = { fg = p.emerald },

	-- ── flash.nvim ────────────────────────────────────────────────────────────
	FlashLabel = { fg = p.void, bg = p.spark, bold = true },
	FlashMatch = { fg = p.void, bg = p.gold, bold = true },
	FlashCurrent = { fg = p.void, bg = p.lava, bold = true },
	FlashBackdrop = { fg = p.ash },
	FlashPrompt = { fg = p.bone, bg = p.shadow },
	FlashPromptMode = { fg = p.lake, bg = p.shadow, bold = true },
	FlashCursor = "Cursor",

	-- ── gitsigns ─────────────────────────────────────────────────────────────
	GitSignsAdd = { fg = p.emerald },
	GitSignsChange = { fg = p.lava },
	GitSignsDelete = { fg = p.danger },
	GitSignsAddNr = { fg = p.emerald },
	GitSignsChangeNr = { fg = p.lava },
	GitSignsDeleteNr = { fg = p.danger },
	GitSignsAddLn = { bg = p.grass, fg = p.air },
	GitSignsChangeLn = { bg = p.oil, fg = p.lava },
	GitSignsDeleteLn = { bg = p.soil, fg = p.air },
	GitSignsAddInline = { fg = p.void, bg = p.emerald },
	GitSignsChangeInline = { fg = p.void, bg = p.lava },
	GitSignsDeleteInline = { fg = p.void, bg = p.danger },

	-- ── snacks.nvim ───────────────────────────────────────────────────────────
	SnacksDashboardHeader = { fg = p.acid, bold = true },
	SnacksDashboardFooter = { fg = p.ash, italic = true },
	SnacksDashboardTitle = { fg = p.lake, bold = true },
	SnacksDashboardDesc = { fg = p.bone },
	SnacksDashboardKey = { fg = p.fungus, bold = true },
	SnacksDashboardIcon = { fg = p.emerald },
	SnacksDashboardDir = { fg = p.ash },
	SnacksDashboardFile = { fg = p.bone },
	SnacksDashboardSpecial = { fg = p.ash },
	SnacksDashboardTerminal = { fg = p.bone },
	SnacksNotifierDebug = { fg = p.ash },
	SnacksNotifierTrace = { fg = p.ash },
	SnacksNotifierInfo = { fg = p.bone },
	SnacksNotifierWarn = { fg = p.lava },
	SnacksNotifierError = { fg = p.danger },
	SnacksNotifierBorderDebug = { fg = p.cloak },
	SnacksNotifierBorderTrace = { fg = p.cloak },
	SnacksNotifierBorderInfo = { fg = p.lake },
	SnacksNotifierBorderWarn = { fg = p.lava },
	SnacksNotifierBorderError = { fg = p.danger },
	SnacksNotifierTitleDebug = { fg = p.ash, bold = true },
	SnacksNotifierTitleTrace = { fg = p.ash, bold = true },
	SnacksNotifierTitleInfo = { fg = p.lake, bold = true },
	SnacksNotifierTitleWarn = { fg = p.lava, bold = true },
	SnacksNotifierTitleError = { fg = p.danger, bold = true },
	SnacksNotifierIconDebug = { fg = p.ash },
	SnacksNotifierIconTrace = { fg = p.ash },
	SnacksNotifierIconInfo = { fg = p.lake },
	SnacksNotifierIconWarn = { fg = p.lava },
	SnacksNotifierIconError = { fg = p.danger },
	SnacksIndent = { fg = p.wall },
	SnacksIndentScope = { fg = p.cloak },
	SnacksPickerDir = { fg = p.ash },
	SnacksPickerFile = { fg = p.bone },
	SnacksPickerMatch = { fg = p.gold, bold = true },
	SnacksPickerSelected = { fg = p.fungus },
	SnacksPickerToggle = { fg = p.lake },
	SnacksPickerInputBorder = { fg = p.cloak },
	SnacksPickerInputTitle = { fg = p.lake, bold = true },
	SnacksPickerListTitle = { fg = p.bone, bold = true },
	SnacksPickerPreviewTitle = { fg = p.ash, bold = true },
	SnacksInputBorder = { fg = p.cloak },
	SnacksInputTitle = { fg = p.lake, bold = true },

	-- ── noice.nvim ────────────────────────────────────────────────────────────
	NoiceCmdline = { fg = p.bone, bg = p.void },
	NoiceCmdlineIcon = { fg = p.lake },
	NoiceCmdlineIconSearch = { fg = p.gold },
	NoiceCmdlinePopup = { fg = p.bone, bg = p.void },
	NoiceCmdlinePopupBorder = { fg = p.cloak },
	NoiceCmdlinePopupBorderSearch = { fg = p.gold },
	NoiceCmdlinePopupTitle = { fg = p.lake, bold = true },
	NoicePopup = { fg = p.bone, bg = p.void },
	NoicePopupBorder = { fg = p.cloak },
	NoiceConfirm = { fg = p.bone, bg = p.void },
	NoiceConfirmBorder = { fg = p.cloak },
	NoiceMini = { fg = p.bone, bg = p.shadow },
	NoiceFormatProgressDone = { fg = p.void, bg = p.lake },
	NoiceFormatProgressTodo = { fg = p.ash, bg = p.shadow },
	NoiceLspProgressSpinner = { fg = p.lake },
	NoiceLspProgressTitle = { fg = p.bone },
	NoiceLspProgressClient = { fg = p.ash },

	-- ── bufferline.nvim ───────────────────────────────────────────────────────
	BufferLineFill = { bg = p.void },
	BufferLineBackground = { fg = p.ash, bg = p.shadow },
	BufferLineBufferVisible = { fg = p.bone, bg = p.shadow },
	BufferLineBufferSelected = { fg = p.bone, bg = p.void, bold = true },
	BufferLineModified = { fg = p.lava, bg = p.shadow },
	BufferLineModifiedVisible = { fg = p.lava, bg = p.shadow },
	BufferLineModifiedSelected = { fg = p.lava, bg = p.void },
	BufferLineError = { fg = p.danger, bg = p.shadow },
	BufferLineErrorVisible = { fg = p.danger, bg = p.shadow },
	BufferLineErrorSelected = { fg = p.danger, bg = p.void },
	BufferLineErrorDiagnostic = { fg = p.danger, bg = p.shadow },
	BufferLineErrorDiagnosticVisible = { fg = p.danger, bg = p.shadow },
	BufferLineErrorDiagnosticSelected = { fg = p.danger, bg = p.void },
	BufferLineWarning = { fg = p.lava, bg = p.shadow },
	BufferLineWarningVisible = { fg = p.lava, bg = p.shadow },
	BufferLineWarningSelected = { fg = p.lava, bg = p.void },
	BufferLineWarningDiagnostic = { fg = p.lava, bg = p.shadow },
	BufferLineWarningDiagnosticVisible = { fg = p.lava, bg = p.shadow },
	BufferLineWarningDiagnosticSelected = { fg = p.lava, bg = p.void },
	BufferLineHint = { fg = p.emerald, bg = p.shadow },
	BufferLineHintVisible = { fg = p.emerald, bg = p.shadow },
	BufferLineHintSelected = { fg = p.emerald, bg = p.void },
	BufferLineHintDiagnostic = { fg = p.emerald, bg = p.shadow },
	BufferLineHintDiagnosticVisible = { fg = p.emerald, bg = p.shadow },
	BufferLineHintDiagnosticSelected = { fg = p.emerald, bg = p.void },
	BufferLineInfo = { fg = p.lake, bg = p.shadow },
	BufferLineInfoVisible = { fg = p.lake, bg = p.shadow },
	BufferLineInfoSelected = { fg = p.lake, bg = p.void },
	BufferLineInfoDiagnostic = { fg = p.lake, bg = p.shadow },
	BufferLineInfoDiagnosticVisible = { fg = p.lake, bg = p.shadow },
	BufferLineInfoDiagnosticSelected = { fg = p.lake, bg = p.void },
	BufferLineSeparator = { fg = p.void, bg = p.shadow },
	BufferLineSeparatorVisible = { fg = p.void, bg = p.shadow },
	BufferLineSeparatorSelected = { fg = p.void, bg = p.void },
	BufferLineIndicatorSelected = { fg = p.lake, bg = p.void },
	BufferLineIndicatorVisible = { fg = p.cloak, bg = p.shadow },
	BufferLinePick = { fg = p.blood, bg = p.shadow, bold = true },
	BufferLinePickSelected = { fg = p.blood, bg = p.void, bold = true },
	BufferLinePickVisible = { fg = p.blood, bg = p.shadow, bold = true },
	BufferLineTabSeparator = { fg = p.void, bg = p.void },
	BufferLineTabSeparatorSelected = { fg = p.void, bg = p.void },
	BufferLineTab = { fg = p.ash, bg = p.void },
	BufferLineTabSelected = { fg = p.bone, bg = p.void, bold = true },
	BufferLineTabClose = { fg = p.ash, bg = p.void },
	BufferLineCloseButton = { fg = p.ash, bg = p.shadow },
	BufferLineCloseButtonVisible = { fg = p.bone, bg = p.shadow },
	BufferLineCloseButtonSelected = { fg = p.danger, bg = p.void },
	BufferLineNumbers = { fg = p.ash, bg = p.shadow },
	BufferLineNumbersVisible = { fg = p.bone, bg = p.shadow },
	BufferLineNumbersSelected = { fg = p.lake, bg = p.void, bold = true },
	BufferLineDuplicate = { fg = p.ash, bg = p.shadow, italic = true },
	BufferLineDuplicateVisible = { fg = p.ash, bg = p.shadow, italic = true },
	BufferLineDuplicateSelected = { fg = p.bone, bg = p.void, italic = true },
	BufferLineGroupLabel = { fg = p.void, bg = p.lake },
	BufferLineGroupSeparator = { fg = p.cloak, bg = p.shadow },
	BufferLineOffset = { fg = p.ash, bg = p.shadow },
	BufferLineTruncMarker = { fg = p.ash, bg = p.shadow },

	-- ── which-key ─────────────────────────────────────────────────────────────
	WhichKey = { fg = p.fungus },
	WhichKeyGroup = { fg = p.lake },
	WhichKeyDesc = { fg = p.bone },
	WhichKeySeparator = { fg = p.ash },
	WhichKeyBorder = { fg = p.cloak },
	WhichKeyNormal = { bg = p.void },
	WhichKeyValue = { fg = p.ash },

	-- ── todo-comments ─────────────────────────────────────────────────────────
	TodoBgTODO = { fg = p.void, bg = p.lake, bold = true },
	TodoBgFIX = { fg = p.void, bg = p.danger, bold = true },
	TodoBgHACK = { fg = p.void, bg = p.lava, bold = true },
	TodoBgWARN = { fg = p.void, bg = p.lava, bold = true },
	TodoBgNOTE = { fg = p.void, bg = p.emerald, bold = true },
	TodoBgPERF = { fg = p.void, bg = p.amber, bold = true },
	TodoBgTEST = { fg = p.void, bg = p.fungus, bold = true },
	TodoFgTODO = { fg = p.lake },
	TodoFgFIX = { fg = p.danger },
	TodoFgHACK = { fg = p.lava },
	TodoFgWARN = { fg = p.lava },
	TodoFgNOTE = { fg = p.emerald },
	TodoFgPERF = { fg = p.amber },
	TodoFgTEST = { fg = p.fungus },
	TodoSignTODO = "TodoFgTODO",
	TodoSignFIX = "TodoFgFIX",
	TodoSignHACK = "TodoFgHACK",
	TodoSignWARN = "TodoFgWARN",
	TodoSignNOTE = "TodoFgNOTE",
	TodoSignPERF = "TodoFgPERF",
	TodoSignTEST = "TodoFgTEST",

	-- ── render-markdown ───────────────────────────────────────────────────────
	RenderMarkdownH1 = { fg = p.lake, bg = p.deep, bold = true },
	RenderMarkdownH2 = { fg = p.emerald, bg = p.grass, bold = true },
	RenderMarkdownH3 = { fg = p.acid, bg = p.grass, bold = true },
	RenderMarkdownH4 = { fg = p.amber, bg = p.oil },
	RenderMarkdownH5 = { fg = p.ash },
	RenderMarkdownH6 = { fg = p.ash },
	RenderMarkdownH1Bg = { bg = p.deep },
	RenderMarkdownH2Bg = { bg = p.grass },
	RenderMarkdownH3Bg = { bg = p.grass },
	RenderMarkdownH4Bg = { bg = p.oil },
	RenderMarkdownH5Bg = { bg = p.shadow },
	RenderMarkdownH6Bg = { bg = p.shadow },
	RenderMarkdownCode = { bg = p.shadow },
	RenderMarkdownCodeInline = { fg = p.bone, bg = p.shadow },
	RenderMarkdownQuote = { fg = p.emerald, italic = true },
	RenderMarkdownDash = { fg = p.cloak },
	RenderMarkdownBullet = { fg = p.lake },
	RenderMarkdownChecked = { fg = p.acid },
	RenderMarkdownUnchecked = { fg = p.ash },
	RenderMarkdownLink = { fg = p.lake, underline = true },
	RenderMarkdownTableHead = { fg = p.lake, bold = true },
	RenderMarkdownTableRow = { fg = p.bone },
	RenderMarkdownTableFill = { fg = p.wall },
}

-- ── Terminal colors ──────────────────────────────────────────────────────────
vim.g.terminal_color_0 = p.void -- black
vim.g.terminal_color_1 = p.blood -- red
vim.g.terminal_color_2 = p.emerald -- green
vim.g.terminal_color_3 = p.amber -- yellow
vim.g.terminal_color_4 = p.lake -- blue
vim.g.terminal_color_5 = p.fungus -- magenta
vim.g.terminal_color_6 = p.sea -- cyan
vim.g.terminal_color_7 = p.bone -- white
vim.g.terminal_color_8 = p.ash -- bright black
vim.g.terminal_color_9 = p.danger -- bright red
vim.g.terminal_color_10 = p.acid -- bright green
vim.g.terminal_color_11 = p.gold -- bright yellow
vim.g.terminal_color_12 = p.fog -- bright blue
vim.g.terminal_color_13 = p.fungus -- bright magenta
vim.g.terminal_color_14 = p.spark -- bright cyan
vim.g.terminal_color_15 = p.air -- bright white

-- ── Apply ────────────────────────────────────────────────────────────────────
for group, spec in pairs(hl) do
	vim.api.nvim_set_hl(0, group, type(spec) == "string" and { link = spec } or spec)
end

