-- cave.lua
-- Neovim colorscheme inspired by Noita and Catppuccin.
-- Palette drawn from the game's potions, materials, and cave atmosphere.

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
	vim.cmd("syntax reset")
end

vim.g.colors_name = "cave"
vim.o.background = "dark"
vim.o.termguicolors = true

local p = {
	-- Cave environments
	cave_rock        = "#0e0c10",
	cave_shadow      = "#130f16",
	cave_deep        = "#080608",
	void             = "#060408",
	cave_wall        = "#2a2432",
	cave_floor       = "#100d14",
	cave_dark        = "#161220",
	cave_lnum        = "#3a3040",
	-- Foregrounds
	bone             = "#d4c8a8",
	ash              = "#6e6458",
	ivory            = "#e8dcc0",
	parchment        = "#907858",
	scroll           = "#c0b090",
	haze             = "#8878a8",
	-- Colors
	emerald          = "#3d8c5a",
	lake             = "#4e8fd4",
	charm            = "#c85ca8",
	acid             = "#9cc028",
	honey            = "#c89030",
	blood            = "#c03838",
	fog              = "#8868c0",
	danger           = "#e03030",
	lava             = "#d46818",
	aura             = "#6a3a9a",
	heal             = "#40b840",
	heal_bright      = "#50b840",
	gold             = "#e8d030",
	spark            = "#20d8f0",
	sea              = "#20b8a0",
	-- Tinted bg shades
	aura_dim         = "#4a2e78",
	aura_deep        = "#2c2048",
	aura_bg          = "#0e1828",
	emerald_bg       = "#0e1410",
	acid_bg          = "#141a06",
	honey_bg         = "#1e1808",
	heal_bg          = "#0e1a0e",
	danger_bg        = "#200e0e",
	-- Diff backgrounds
	diff_add         = "#1a3820",
	diff_del         = "#2e1212",
	diff_change      = "#1a2e4a",
}

-- ── Semantic assignments ──────────────────────────────────────────────────────
local c = {
	bg1          = p.cave_rock,
	bg2          = p.cave_shadow,
	bg3          = p.cave_deep,
	bg4          = p.void,
	bg_alt       = p.cave_wall,
	act1         = p.cave_floor,
	act2         = p.aura,
	base         = p.bone,
	base_dim     = p.ash,
	cursor       = p.ivory,
	border       = p.aura,
	cblk         = p.scroll,
	cblk_bg      = p.cave_dark,
	comment      = p.emerald,
	comment_bg   = p.emerald_bg,
	const        = p.honey,
	err          = p.danger,
	func         = p.charm,
	head1        = p.lake,
	head1_bg     = p.aura_bg,
	head2        = p.emerald,
	head2_bg     = p.emerald_bg,
	head3        = p.acid,
	head3_bg     = p.acid_bg,
	head4        = p.honey,
	head4_bg     = p.honey_bg,
	highlight    = p.aura_dim,
	highlight_dim = p.aura_deep,
	keyword      = p.lake,
	lnum         = p.cave_lnum,
	mat          = p.gold,
	meta         = p.parchment,
	str          = p.acid,
	suc          = p.heal,
	ttip         = p.haze,
	ttip_sl      = p.lake,
	type         = p.blood,
	var          = p.fog,
	war          = p.lava,
	green        = p.heal_bright,
	green_bg     = p.heal_bg,
	green_bg_s   = p.diff_add,
	red          = p.danger,
	red_bg       = p.danger_bg,
	red_bg_s     = p.diff_del,
	blue_bg_s    = p.diff_change,
	yellow_bg    = p.honey_bg,
}

-- ── Highlight table ──────────────────────────────────────────────────────────
-- String values are treated as links in the apply loop below.
local hl = {

	-- ── Base Vim ──────────────────────────────────────────────────────────────
	Normal = { fg = c.base, bg = c.bg2 },
	NormalNC = "Normal",
	NormalFloat = { fg = c.base, bg = c.bg4 },
	FloatBorder = { fg = c.border, bg = c.bg4 },
	FloatTitle = { fg = c.keyword, bg = c.bg4, bold = true },
	ColorColumn = { bg = c.bg2 },
	Conceal = { fg = c.base_dim },
	Cursor = { fg = c.bg1, bg = c.cursor },
	lCursor = "Cursor",
	CursorIM = "Cursor",
	CursorLine = { bg = c.highlight_dim },
	CursorColumn = { bg = c.highlight_dim },
	CursorLineNr = { fg = c.keyword, bold = true },
	Directory = { fg = c.keyword },
	DiffAdd = { bg = c.green_bg_s },
	DiffChange = { bg = c.blue_bg_s },
	DiffDelete = { bg = c.red_bg_s },
	DiffText = { bg = c.blue_bg_s, bold = true },
	EndOfBuffer = { fg = c.bg3 },
	ErrorMsg = { fg = c.err, bold = true },
	VertSplit = { fg = c.border, bg = c.bg1 },
	WinSeparator = { fg = c.border, bg = c.bg1 },
	Folded = { fg = c.base_dim, bg = c.bg2 },
	FoldColumn = { fg = c.lnum, bg = c.bg1 },
	SignColumn = { fg = c.base, bg = c.bg1 },
	IncSearch = { fg = c.bg1, bg = c.war, bold = true },
	Substitute = { fg = c.bg1, bg = p.blood, bold = true },
	LineNr = { fg = c.lnum },
	LineNrAbove = { fg = c.lnum },
	LineNrBelow = { fg = c.lnum },
	MatchParen = { fg = c.mat, bold = true, underline = true },
	ModeMsg = { fg = c.keyword, bold = true },
	MsgArea = { fg = c.base },
	MsgSeparator = { fg = c.border },
	MoreMsg = { fg = c.suc },
	NonText = { fg = p.haze },
	Pmenu = { fg = c.ttip, bg = c.bg4 },
	PmenuSel = { fg = c.base, bg = c.ttip_sl },
	PmenuSbar = { bg = c.bg2 },
	PmenuThumb = { bg = c.act2 },
	PmenuKind = { fg = c.type, bg = c.bg4 },
	PmenuKindSel = { fg = c.type, bg = c.ttip_sl },
	PmenuExtra = { fg = c.base_dim, bg = c.bg4 },
	PmenuExtraSel = { fg = c.base_dim, bg = c.ttip_sl },
	Question = { fg = c.keyword },
	QuickFixLine = { bg = c.highlight_dim },
	Search = { fg = c.bg1, bg = c.mat, bold = true },
	SpecialKey = { fg = c.base_dim },
	SpellBad = { undercurl = true, sp = c.err },
	SpellCap = { undercurl = true, sp = c.war },
	SpellLocal = { undercurl = true, sp = c.comment },
	SpellRare = { undercurl = true, sp = c.const },
	StatusLine = { fg = c.base, bg = c.act1 },
	StatusLineNC = { fg = c.base_dim, bg = c.act1 },
	TabLine = { fg = c.base_dim, bg = c.bg2 },
	TabLineFill = { bg = c.bg2 },
	TabLineSel = { fg = c.base, bg = c.act2 },
	Title = { fg = c.keyword, bold = true },
	Visual = { bg = c.highlight },
	VisualNOS = { bg = c.highlight },
	WarningMsg = { fg = c.war, bold = true },
	Whitespace = { fg = c.bg_alt },
	WildMenu = { fg = c.base, bg = c.act2 },
	WinBar = { fg = c.base, bg = c.bg2 },
	WinBarNC = { fg = c.base_dim, bg = c.bg2 },

	-- ── Syntax ────────────────────────────────────────────────────────────────
	Comment = { fg = c.comment, italic = true },
	Constant = { fg = c.const },
	String = { fg = c.str },
	Character = { fg = c.str },
	Number = { fg = c.const },
	Boolean = { fg = c.const },
	Float = { fg = c.const },
	Identifier = { fg = c.var },
	Function = { fg = c.func },
	Statement = { fg = c.keyword },
	Conditional = { fg = c.keyword },
	Repeat = { fg = c.keyword },
	Label = { fg = c.keyword },
	Operator = { fg = c.base },
	Keyword = { fg = c.keyword },
	Exception = { fg = c.type },
	PreProc = { fg = c.keyword },
	Include = { fg = c.keyword },
	Define = { fg = c.keyword },
	Macro = { fg = c.keyword },
	PreCondit = { fg = c.keyword },
	Type = { fg = c.type },
	StorageClass = { fg = c.type },
	Structure = { fg = c.type },
	Typedef = { fg = c.type },
	Special = { fg = c.const },
	SpecialChar = { fg = c.str },
	Tag = { fg = c.keyword },
	Delimiter = { fg = c.base },
	SpecialComment = { fg = c.comment, italic = true },
	Debug = { fg = c.war },
	Underlined = { underline = true },
	Ignore = { fg = c.base_dim },
	Error = { fg = c.err, bold = true },
	Todo = { fg = c.bg1, bg = c.keyword, bold = true },

	-- ── Treesitter ────────────────────────────────────────────────────────────
	["@variable"] = { fg = c.var },
	["@variable.builtin"] = { fg = c.keyword },
	["@variable.parameter"] = { fg = c.var },
	["@variable.member"] = { fg = c.var },
	["@constant"] = { fg = c.const },
	["@constant.builtin"] = { fg = c.const, bold = true },
	["@constant.macro"] = { fg = c.const },
	["@module"] = { fg = c.base },
	["@module.builtin"] = { fg = c.keyword },
	["@label"] = { fg = c.keyword },
	["@string"] = { fg = c.str },
	["@string.documentation"] = { fg = c.str, italic = true },
	["@string.regexp"] = { fg = c.war },
	["@string.escape"] = { fg = c.type },
	["@string.special"] = { fg = c.const },
	["@string.special.symbol"] = { fg = c.const },
	["@string.special.url"] = { fg = p.sea, underline = true },
	["@character"] = { fg = c.str },
	["@character.special"] = { fg = c.const },
	["@number"] = { fg = c.const },
	["@number.float"] = { fg = c.const },
	["@boolean"] = { fg = c.const, bold = true },
	["@function"] = { fg = c.func },
	["@function.builtin"] = { fg = c.func, bold = true },
	["@function.call"] = { fg = c.func },
	["@function.macro"] = { fg = c.func },
	["@function.method"] = { fg = c.func },
	["@function.method.call"] = { fg = c.func },
	["@constructor"] = { fg = c.type },
	["@operator"] = { fg = c.base },
	["@keyword"] = { fg = c.keyword },
	["@keyword.coroutine"] = { fg = c.keyword },
	["@keyword.function"] = { fg = c.keyword },
	["@keyword.operator"] = { fg = c.keyword },
	["@keyword.import"] = { fg = c.keyword },
	["@keyword.storage"] = { fg = c.type },
	["@keyword.repeat"] = { fg = c.keyword },
	["@keyword.return"] = { fg = c.keyword },
	["@keyword.debug"] = { fg = c.war },
	["@keyword.exception"] = { fg = c.type },
	["@keyword.conditional"] = { fg = c.keyword },
	["@keyword.conditional.ternary"] = { fg = c.keyword },
	["@keyword.directive"] = { fg = c.keyword },
	["@keyword.directive.define"] = { fg = c.keyword },
	["@punctuation.delimiter"] = { fg = c.base_dim },
	["@punctuation.bracket"] = { fg = c.base },
	["@punctuation.special"] = { fg = c.type },
	["@comment"] = { fg = c.comment, italic = true },
	["@comment.documentation"] = { fg = c.comment, italic = true },
	["@comment.error"] = { fg = c.err, bold = true },
	["@comment.warning"] = { fg = c.war, bold = true },
	["@comment.todo"] = { fg = c.bg1, bg = c.keyword, bold = true },
	["@comment.note"] = { fg = c.bg1, bg = c.comment, bold = true },
	["@type"] = { fg = c.type },
	["@type.builtin"] = { fg = c.type, bold = true },
	["@type.definition"] = { fg = c.type },
	["@attribute"] = { fg = c.meta },
	["@attribute.builtin"] = { fg = c.meta },
	["@property"] = { fg = c.var },
	["@tag"] = { fg = c.keyword },
	["@tag.builtin"] = { fg = c.keyword },
	["@tag.attribute"] = { fg = c.var },
	["@tag.delimiter"] = { fg = c.base_dim },
	["@diff.plus"] = { fg = c.green, bg = c.green_bg_s },
	["@diff.minus"] = { fg = c.red, bg = c.red_bg_s },
	["@diff.delta"] = { fg = c.keyword, bg = c.blue_bg_s },
	["@markup.strong"] = { bold = true },
	["@markup.italic"] = { italic = true },
	["@markup.strikethrough"] = { strikethrough = true },
	["@markup.underline"] = { underline = true },
	["@markup.heading"] = { fg = c.head1, bold = true },
	["@markup.heading.1"] = { fg = c.head1, bold = true },
	["@markup.heading.2"] = { fg = c.head2, bold = true },
	["@markup.heading.3"] = { fg = c.head3, bold = true },
	["@markup.heading.4"] = { fg = c.head4 },
	["@markup.heading.5"] = { fg = c.meta },
	["@markup.heading.6"] = { fg = c.base_dim },
	["@markup.quote"] = { fg = c.comment, italic = true },
	["@markup.math"] = { fg = c.type },
	["@markup.link"] = { fg = c.keyword, underline = true },
	["@markup.link.label"] = { fg = c.keyword },
	["@markup.link.url"] = { fg = p.sea, underline = true },
	["@markup.raw"] = { fg = c.cblk, bg = c.cblk_bg },
	["@markup.raw.block"] = { fg = c.cblk, bg = c.cblk_bg },
	["@markup.list"] = { fg = c.keyword },
	["@markup.list.checked"] = { fg = c.str },
	["@markup.list.unchecked"] = { fg = c.base_dim },

	-- ── LSP semantic tokens ───────────────────────────────────────────────────
	["@lsp.type.class"] = "@type",
	["@lsp.type.comment"] = "@comment",
	["@lsp.type.decorator"] = "@attribute",
	["@lsp.type.enum"] = "@type",
	["@lsp.type.enumMember"] = "@constant",
	["@lsp.type.event"] = "@type",
	["@lsp.type.function"] = "@function",
	["@lsp.type.interface"] = "@type",
	["@lsp.type.keyword"] = "@keyword",
	["@lsp.type.macro"] = "@constant.macro",
	["@lsp.type.method"] = "@function.method",
	["@lsp.type.modifier"] = "@keyword",
	["@lsp.type.namespace"] = "@module",
	["@lsp.type.number"] = "@number",
	["@lsp.type.operator"] = "@operator",
	["@lsp.type.parameter"] = "@variable.parameter",
	["@lsp.type.property"] = "@property",
	["@lsp.type.regexp"] = "@string.regexp",
	["@lsp.type.string"] = "@string",
	["@lsp.type.struct"] = "@type",
	["@lsp.type.type"] = "@type",
	["@lsp.type.typeParameter"] = "@type",
	["@lsp.type.variable"] = "@variable",
	["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
	["@lsp.typemod.variable.defaultLibrary"] = "@variable.builtin",
	["@lsp.typemod.type.defaultLibrary"] = "@type.builtin",

	-- ── Diagnostics ───────────────────────────────────────────────────────────
	DiagnosticError = { fg = c.err },
	DiagnosticWarn = { fg = c.war },
	DiagnosticInfo = { fg = c.keyword },
	DiagnosticHint = { fg = c.comment },
	DiagnosticOk = { fg = c.suc },
	DiagnosticVirtualTextError = { fg = c.err, bg = c.red_bg, italic = true },
	DiagnosticVirtualTextWarn = { fg = c.war, bg = c.yellow_bg, italic = true },
	DiagnosticVirtualTextInfo = { fg = c.keyword, bg = c.head1_bg, italic = true },
	DiagnosticVirtualTextHint = { fg = c.comment, bg = c.comment_bg, italic = true },
	DiagnosticVirtualTextOk = { fg = c.suc, bg = c.green_bg, italic = true },
	DiagnosticUnderlineError = { undercurl = true, sp = c.err },
	DiagnosticUnderlineWarn = { undercurl = true, sp = c.war },
	DiagnosticUnderlineInfo = { undercurl = true, sp = c.keyword },
	DiagnosticUnderlineHint = { undercurl = true, sp = c.comment },
	DiagnosticUnderlineOk = { undercurl = true, sp = c.suc },
	DiagnosticFloatingError = { fg = c.err },
	DiagnosticFloatingWarn = { fg = c.war },
	DiagnosticFloatingInfo = { fg = c.keyword },
	DiagnosticFloatingHint = { fg = c.comment },
	DiagnosticSignError = { fg = c.err },
	DiagnosticSignWarn = { fg = c.war },
	DiagnosticSignInfo = { fg = c.keyword },
	DiagnosticSignHint = { fg = c.comment },

	-- ── flash.nvim ────────────────────────────────────────────────────────────
	FlashLabel = { fg = c.bg1, bg = p.spark, bold = true },
	FlashMatch = { fg = c.bg1, bg = c.mat, bold = true },
	FlashCurrent = { fg = c.bg1, bg = c.war, bold = true },
	FlashBackdrop = { fg = c.base_dim },
	FlashPrompt = { fg = c.base, bg = c.act1 },
	FlashPromptMode = { fg = c.keyword, bg = c.act1, bold = true },
	FlashCursor = "Cursor",

	-- ── gitsigns ─────────────────────────────────────────────────────────────
	GitSignsAdd = { fg = c.green },
	GitSignsChange = { fg = c.keyword },
	GitSignsDelete = { fg = c.red },
	GitSignsAddNr = { fg = c.green },
	GitSignsChangeNr = { fg = c.keyword },
	GitSignsDeleteNr = { fg = c.red },
	GitSignsAddLn = { bg = c.green_bg_s },
	GitSignsChangeLn = { bg = c.blue_bg_s },
	GitSignsDeleteLn = { bg = c.red_bg_s },
	GitSignsAddInline = { fg = c.bg1, bg = c.green },
	GitSignsChangeInline = { fg = c.bg1, bg = c.keyword },
	GitSignsDeleteInline = { fg = c.bg1, bg = c.red },

	-- ── snacks.nvim ───────────────────────────────────────────────────────────
	-- Dashboard header gradient: gold (#c89030) → red (#e03030)
	Gradient1 = { fg = "#c89030" },
	Gradient2 = { fg = "#cd7d30" },
	Gradient3 = { fg = "#d26a30" },
	Gradient4 = { fg = "#d65630" },
	Gradient5 = { fg = "#db4330" },
	Gradient6 = { fg = "#e03030" },
	SnacksDashboardHeader = { fg = p.acid, bold = true },
	SnacksDashboardFooter = { fg = c.base_dim, italic = true },
	SnacksDashboardTitle = { fg = c.keyword, bold = true },
	SnacksDashboardDesc = { fg = c.base },
	SnacksDashboardKey = { fg = p.charm, bold = true },
	SnacksDashboardIcon = { fg = c.comment },
	SnacksDashboardDir = { fg = c.base_dim },
	SnacksDashboardFile = { fg = c.base },
	SnacksDashboardSpecial = { fg = c.meta },
	SnacksDashboardTerminal = { fg = c.base },
	SnacksNotifierDebug = { fg = c.base_dim },
	SnacksNotifierTrace = { fg = c.base_dim },
	SnacksNotifierInfo = { fg = c.base },
	SnacksNotifierWarn = { fg = c.war },
	SnacksNotifierError = { fg = c.err },
	SnacksNotifierBorderDebug = { fg = c.border },
	SnacksNotifierBorderTrace = { fg = c.border },
	SnacksNotifierBorderInfo = { fg = c.keyword },
	SnacksNotifierBorderWarn = { fg = c.war },
	SnacksNotifierBorderError = { fg = c.err },
	SnacksNotifierTitleDebug = { fg = c.base_dim, bold = true },
	SnacksNotifierTitleTrace = { fg = c.base_dim, bold = true },
	SnacksNotifierTitleInfo = { fg = c.keyword, bold = true },
	SnacksNotifierTitleWarn = { fg = c.war, bold = true },
	SnacksNotifierTitleError = { fg = c.err, bold = true },
	SnacksNotifierIconDebug = { fg = c.base_dim },
	SnacksNotifierIconTrace = { fg = c.base_dim },
	SnacksNotifierIconInfo = { fg = c.keyword },
	SnacksNotifierIconWarn = { fg = c.war },
	SnacksNotifierIconError = { fg = c.err },
	SnacksIndent = { fg = c.bg_alt },
	SnacksIndentScope = { fg = c.act2 },
	SnacksPickerDir = { fg = c.base_dim },
	SnacksPickerFile = { fg = c.base },
	SnacksPickerMatch = { fg = c.mat, bold = true },
	SnacksPickerSelected = { fg = p.charm },
	SnacksPickerToggle = { fg = c.keyword },
	SnacksPickerInputBorder = { fg = c.border },
	SnacksPickerInputTitle = { fg = c.keyword, bold = true },
	SnacksPickerListTitle = { fg = c.base, bold = true },
	SnacksPickerPreviewTitle = { fg = c.base_dim, bold = true },
	SnacksInputBorder = { fg = c.border },
	SnacksInputTitle = { fg = c.keyword, bold = true },

	-- ── noice.nvim ────────────────────────────────────────────────────────────
	NoiceCmdline = { fg = c.base, bg = c.bg1 },
	NoiceCmdlineIcon = { fg = c.keyword },
	NoiceCmdlineIconSearch = { fg = c.mat },
	NoiceCmdlinePopup = { fg = c.base, bg = c.bg4 },
	NoiceCmdlinePopupBorder = { fg = c.border },
	NoiceCmdlinePopupBorderSearch = { fg = c.mat },
	NoiceCmdlinePopupTitle = { fg = c.keyword, bold = true },
	NoicePopup = { fg = c.base, bg = c.bg4 },
	NoicePopupBorder = { fg = c.border },
	NoiceConfirm = { fg = c.base, bg = c.bg4 },
	NoiceConfirmBorder = { fg = c.border },
	NoiceMini = { fg = c.base, bg = c.act1 },
	NoiceFormatProgressDone = { fg = c.bg1, bg = c.keyword },
	NoiceFormatProgressTodo = { fg = c.base_dim, bg = c.bg2 },
	NoiceLspProgressSpinner = { fg = c.keyword },
	NoiceLspProgressTitle = { fg = c.base },
	NoiceLspProgressClient = { fg = c.base_dim },

	-- ── bufferline.nvim ───────────────────────────────────────────────────────
	BufferLineFill = { bg = c.bg3 },
	BufferLineBackground = { fg = c.base_dim, bg = c.bg2 },
	BufferLineBufferVisible = { fg = c.base, bg = c.act1 },
	BufferLineBufferSelected = { fg = c.base, bg = c.bg1, bold = true },
	BufferLineModified = { fg = c.war, bg = c.bg2 },
	BufferLineModifiedVisible = { fg = c.war, bg = c.act1 },
	BufferLineModifiedSelected = { fg = c.war, bg = c.bg1 },
	BufferLineError = { fg = c.err, bg = c.bg2 },
	BufferLineErrorVisible = { fg = c.err, bg = c.act1 },
	BufferLineErrorSelected = { fg = c.err, bg = c.bg1 },
	BufferLineErrorDiagnostic = { fg = c.err, bg = c.bg2 },
	BufferLineErrorDiagnosticVisible = { fg = c.err, bg = c.act1 },
	BufferLineErrorDiagnosticSelected = { fg = c.err, bg = c.bg1 },
	BufferLineWarning = { fg = c.war, bg = c.bg2 },
	BufferLineWarningVisible = { fg = c.war, bg = c.act1 },
	BufferLineWarningSelected = { fg = c.war, bg = c.bg1 },
	BufferLineWarningDiagnostic = { fg = c.war, bg = c.bg2 },
	BufferLineWarningDiagnosticVisible = { fg = c.war, bg = c.act1 },
	BufferLineWarningDiagnosticSelected = { fg = c.war, bg = c.bg1 },
	BufferLineHint = { fg = c.comment, bg = c.bg2 },
	BufferLineHintVisible = { fg = c.comment, bg = c.act1 },
	BufferLineHintSelected = { fg = c.comment, bg = c.bg1 },
	BufferLineHintDiagnostic = { fg = c.comment, bg = c.bg2 },
	BufferLineHintDiagnosticVisible = { fg = c.comment, bg = c.act1 },
	BufferLineHintDiagnosticSelected = { fg = c.comment, bg = c.bg1 },
	BufferLineInfo = { fg = c.keyword, bg = c.bg2 },
	BufferLineInfoVisible = { fg = c.keyword, bg = c.act1 },
	BufferLineInfoSelected = { fg = c.keyword, bg = c.bg1 },
	BufferLineInfoDiagnostic = { fg = c.keyword, bg = c.bg2 },
	BufferLineInfoDiagnosticVisible = { fg = c.keyword, bg = c.act1 },
	BufferLineInfoDiagnosticSelected = { fg = c.keyword, bg = c.bg1 },
	BufferLineSeparator = { fg = c.bg3, bg = c.bg2 },
	BufferLineSeparatorVisible = { fg = c.bg3, bg = c.act1 },
	BufferLineSeparatorSelected = { fg = c.bg3, bg = c.bg1 },
	BufferLineIndicatorSelected = { fg = c.keyword, bg = c.bg1 },
	BufferLineIndicatorVisible = { fg = c.act2, bg = c.act1 },
	BufferLinePick = { fg = p.blood, bg = c.bg2, bold = true },
	BufferLinePickSelected = { fg = p.blood, bg = c.bg1, bold = true },
	BufferLinePickVisible = { fg = p.blood, bg = c.act1, bold = true },
	BufferLineTabSeparator = { fg = c.bg3, bg = c.bg3 },
	BufferLineTabSeparatorSelected = { fg = c.bg3, bg = c.bg1 },
	BufferLineTab = { fg = c.base_dim, bg = c.bg3 },
	BufferLineTabSelected = { fg = c.base, bg = c.bg1, bold = true },
	BufferLineTabClose = { fg = c.base_dim, bg = c.bg3 },
	BufferLineCloseButton = { fg = c.base_dim, bg = c.bg2 },
	BufferLineCloseButtonVisible = { fg = c.base, bg = c.act1 },
	BufferLineCloseButtonSelected = { fg = c.err, bg = c.bg1 },
	BufferLineNumbers = { fg = c.base_dim, bg = c.bg2 },
	BufferLineNumbersVisible = { fg = c.base, bg = c.act1 },
	BufferLineNumbersSelected = { fg = c.keyword, bg = c.bg1, bold = true },
	BufferLineDuplicate = { fg = c.base_dim, bg = c.bg2, italic = true },
	BufferLineDuplicateVisible = { fg = c.base_dim, bg = c.act1, italic = true },
	BufferLineDuplicateSelected = { fg = c.base, bg = c.bg1, italic = true },
	BufferLineGroupLabel = { fg = c.bg1, bg = c.keyword },
	BufferLineGroupSeparator = { fg = c.border, bg = c.bg2 },
	BufferLineOffset = { fg = c.base_dim, bg = c.bg2 },
	BufferLineTruncMarker = { fg = c.base_dim, bg = c.bg2 },

	-- ── which-key ─────────────────────────────────────────────────────────────
	WhichKey = { fg = p.charm },
	WhichKeyGroup = { fg = c.keyword },
	WhichKeyDesc = { fg = c.base },
	WhichKeySeparator = { fg = c.base_dim },
	WhichKeyBorder = { fg = c.border },
	WhichKeyNormal = { bg = c.bg4 },
	WhichKeyValue = { fg = c.base_dim },

	-- ── trouble.nvim ──────────────────────────────────────────────────────────
	TroubleNormal = { fg = c.base, bg = c.bg2 },
	TroubleNormalNC = { fg = c.base, bg = c.bg2 },
	TroubleText = { fg = c.base },
	TroubleCount = { fg = p.charm, bg = c.bg2, bold = true },
	TroubleFileName = { fg = c.comment },
	TroubleIconArray = { fg = c.type },
	TroubleIconBoolean = { fg = c.const },
	TroubleIconClass = { fg = c.type },
	TroubleIconConstant = { fg = c.const },
	TroubleIconConstructor = { fg = c.type },
	TroubleIconEnum = { fg = c.type },
	TroubleIconEnumMember = { fg = c.const },
	TroubleIconEvent = { fg = c.type },
	TroubleIconField = { fg = c.var },
	TroubleIconFile = { fg = c.comment },
	TroubleIconFunction = { fg = c.func },
	TroubleIconInterface = { fg = c.type },
	TroubleIconKey = { fg = c.keyword },
	TroubleIconMethod = { fg = c.func },
	TroubleIconModule = { fg = c.base },
	TroubleIconNamespace = { fg = c.base },
	TroubleIconNull = { fg = c.const },
	TroubleIconNumber = { fg = c.const },
	TroubleIconObject = { fg = c.type },
	TroubleIconOperator = { fg = c.base },
	TroubleIconPackage = { fg = c.base },
	TroubleIconProperty = { fg = c.var },
	TroubleIconString = { fg = c.str },
	TroubleIconStruct = { fg = c.type },
	TroubleIconTypeParameter = { fg = c.type },
	TroubleIconVariable = { fg = c.var },
	TroubleSignError = { fg = c.err },
	TroubleSignWarn = { fg = c.war },
	TroubleSignInfo = { fg = c.keyword },
	TroubleSignHint = { fg = c.comment },

	-- ── todo-comments ─────────────────────────────────────────────────────────
	TodoBgTODO = { fg = c.bg1, bg = c.keyword, bold = true },
	TodoBgFIX = { fg = c.bg1, bg = c.err, bold = true },
	TodoBgHACK = { fg = c.bg1, bg = c.war, bold = true },
	TodoBgWARN = { fg = c.bg1, bg = c.war, bold = true },
	TodoBgNOTE = { fg = c.bg1, bg = c.comment, bold = true },
	TodoBgPERF = { fg = c.bg1, bg = c.const, bold = true },
	TodoBgTEST = { fg = c.bg1, bg = p.charm, bold = true },
	TodoFgTODO = { fg = c.keyword },
	TodoFgFIX = { fg = c.err },
	TodoFgHACK = { fg = c.war },
	TodoFgWARN = { fg = c.war },
	TodoFgNOTE = { fg = c.comment },
	TodoFgPERF = { fg = c.const },
	TodoFgTEST = { fg = p.charm },
	TodoSignTODO = "TodoFgTODO",
	TodoSignFIX = "TodoFgFIX",
	TodoSignHACK = "TodoFgHACK",
	TodoSignWARN = "TodoFgWARN",
	TodoSignNOTE = "TodoFgNOTE",
	TodoSignPERF = "TodoFgPERF",
	TodoSignTEST = "TodoFgTEST",

	-- ── render-markdown ───────────────────────────────────────────────────────
	RenderMarkdownH1 = { fg = c.head1, bg = c.head1_bg, bold = true },
	RenderMarkdownH2 = { fg = c.head2, bg = c.head2_bg, bold = true },
	RenderMarkdownH3 = { fg = c.head3, bg = c.head3_bg, bold = true },
	RenderMarkdownH4 = { fg = c.head4, bg = c.head4_bg },
	RenderMarkdownH5 = { fg = c.meta },
	RenderMarkdownH6 = { fg = c.base_dim },
	RenderMarkdownH1Bg = { bg = c.head1_bg },
	RenderMarkdownH2Bg = { bg = c.head2_bg },
	RenderMarkdownH3Bg = { bg = c.head3_bg },
	RenderMarkdownH4Bg = { bg = c.head4_bg },
	RenderMarkdownH5Bg = { bg = c.bg2 },
	RenderMarkdownH6Bg = { bg = c.bg2 },
	RenderMarkdownCode = { bg = c.cblk_bg },
	RenderMarkdownCodeInline = { fg = c.cblk, bg = c.cblk_bg },
	RenderMarkdownQuote = { fg = c.comment, italic = true },
	RenderMarkdownDash = { fg = c.border },
	RenderMarkdownBullet = { fg = c.keyword },
	RenderMarkdownChecked = { fg = c.str },
	RenderMarkdownUnchecked = { fg = c.base_dim },
	RenderMarkdownLink = { fg = c.keyword, underline = true },
	RenderMarkdownTableHead = { fg = c.keyword, bold = true },
	RenderMarkdownTableRow = { fg = c.base },
	RenderMarkdownTableFill = { fg = c.bg_alt },
}

-- ── Terminal colors ──────────────────────────────────────────────────────────
vim.g.terminal_color_0 = c.bg1 -- black
vim.g.terminal_color_1 = c.err -- red
vim.g.terminal_color_2 = c.str -- green
vim.g.terminal_color_3 = p.honey -- yellow
vim.g.terminal_color_4 = c.keyword -- blue
vim.g.terminal_color_5 = c.func -- magenta
vim.g.terminal_color_6 = p.sea -- cyan
vim.g.terminal_color_7 = p.bone -- white
vim.g.terminal_color_8 = p.ash -- bright black
vim.g.terminal_color_9 = p.danger -- bright red
vim.g.terminal_color_10 = p.gold -- bright green
vim.g.terminal_color_11 = p.honey -- bright yellow
vim.g.terminal_color_12 = p.fog -- bright blue
vim.g.terminal_color_13 = c.func -- bright magenta
vim.g.terminal_color_14 = p.spark -- bright cyan
vim.g.terminal_color_15 = p.ivory -- bright white

-- ── Apply ────────────────────────────────────────────────────────────────────
for group, spec in pairs(hl) do
	vim.api.nvim_set_hl(0, group, type(spec) == "string" and { link = spec } or spec)
end

